### ISSUE TITLE
请问这里收益率的计算公式是？

### ISSUE THREAD

**Issue by BruceZhaoR** [renkun-ken/r-data-practice#1]

**Comment by renkun-ken** [comment]
日收益率 `ret = close / pre_close - 1`

**Comment by BruceZhaoR** [comment]
> 当日股票涨跌幅可以用 `close / pre_close - 1` 计算得到

也就是说这里的`日涨跌幅`和`日收益率`是等价的？

`行业收益率`，`市场收益率`，`股票收益率`，任老师能否也给出计算公式，方便外行人士参与训练. :pray:

**Comment by renkun-ken** [comment]
我还是改改文档吧, 收益率和涨跌幅是同一个意思.

市场收益率就是所有股票的市值加权收益率, 行业收益率就是该行业内所有股票的市值加权收益率.
