### ISSUE TITLE
Will there be any answers later? 

### ISSUE THREAD

**Issue by baifengbai** [renkun-ken/r-data-practice#2]

**Comment by renkun-ken** [comment]
There probably won't be standard answers but users may contribute their answers somehow. I'll think about it and update this later.

**Comment by keepdrinking** [comment]
没有答案吗呜呜

**Comment by renkun-ken** [comment]
I'm considering to restructure this project so that more data, more questions, and more answers with different approaches (e.g. data.table, tidyverse) could be demonstrated. But no time to do this yet.
